
Vagrant::configure("2") do |config|

  # enable cachier
  #config.cache.scope = :box

  # the Chef version to use
  config.omnibus.chef_version = "12.0.3"

  # enable berkshelf plugin
  config.berkshelf.enabled = true

  # configure the basebox
  config.vm.box = "opscode-centos-6.5"

  #
  # define the VM
  #
  config.vm.define :'bt_base' do | config |

    # configure host-only network
    config.vm.hostname = "btbase.local"
    config.vm.network :private_network, ip: "172.16.40.15"

    # virtualbox-specific customizations
    config.vm.provider :virtualbox do |vbox, override|
      vbox.customize ["modifyvm", :id, "--name", "btbase.local"]
    end

    # provisioning
    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "bt_base"
      chef.log_level = :info
    end
  end
end
