
Vagrant::configure("2") do |config|

  # enable cachier
  #config.cache.scope = :box

  # the Chef version to use
  config.omnibus.chef_version = "12.0.3"

  # enable berkshelf plugin
  config.berkshelf.enabled = true

  # configure the basebox
  config.vm.box = "opscode-centos-6.5"

  #
  # define the VM
  #
  config.vm.define :'bt_tomcat' do | config |

    # configure host-only network
    config.vm.hostname = "bttomcat.local"
#    config.vm.network :private_network, ip: "172.16.40.15"

    # virtualbox-specific customizations
    config.vm.provider :virtualbox do |vbox, override|
      vbox.customize ["modifyvm", :id, "--name", "bttomcat.local"]
    end

    # provisioning
    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "bt_tomcat"
      chef.log_level = :info
      chef.data_bags_path = "../../environment-cookbooks/bt_env_deploy_ui_stack/data_bags"
    end
  end
end
