---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  data_bags_path: "test/data_bags"

platforms:
  - name: centos-6.5
    driver:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[bt_tomcat::default]
    attributes:
