---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: info

platforms:
  - name: centos-6.5
    driver:
      network:
      - ["forwarded_port", {guest: 8153, host: 8153}]
      - ["forwarded_port", {guest: 8154, host: 8154}]

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[bt_go::default]
    attributes:
