---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      network:
      - ["forwarded_port", {guest: 9000, host: 9000}]

suites:
  - name: default
    run_list:
      - recipe[bt_sonarqube::default]
    attributes:
