
Vagrant::configure("2") do |config|

  # the Chef version to use
  config.omnibus.chef_version = "12.0.3"

  # disable vagrant-berkshelf
  config.berkshelf.enabled = false

  # common baseboxes for all VMs
  config.vm.box = "opscode-centos-6.5"

  #
  # Gitlab
  #
  config.vm.define :'gitlab' do |config|

    config.toplevel_cookbook.url = "file:////home/john/work/BT/chef/top-level-cookbooks/bt_gitlab"

    config.vm.hostname = "gitlab.local"

    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "bt_env_build_stack::gitlab"
      chef.environments_path = "./environments"
      chef.environment = "local"
      chef.roles_path = "./roles"
    end
  end

  #
  # Go Server
  #
  config.vm.define :'go-server' do |config|

    config.toplevel_cookbook.url = "file:////home/john/work/BT/chef/top-level-cookbooks/bt_go"
    config.vm.hostname = "goserver.local"

    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "bt_go::server"
      chef.environments_path = "./environments"
      chef.environment = "local"
      chef.roles_path = "./roles"
    end
  end

  #
  # Go Agent
  #
  config.vm.define :'go-agent' do |config|

    config.toplevel_cookbook.url = "file:////home/john/work/BT/chef/top-level-cookbooks/bt_go"
    config.vm.hostname = "goagent.local"

    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "bt_go::agent"
      chef.environments_path = "./environments"
      chef.environment = "local"
      chef.roles_path = "./roles"
    end
  end

end
