---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      network:
      - ["forwarded_port", {guest: 80, host: 80}]

suites:
  - name: default
    run_list:
      - recipe[bt_apache2::default]
    attributes:
