---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver:
      network:
      - ["forwarded_port", {guest: 8081, host: 8081}]
suites:
  - name: default
    run_list:
      - recipe[bt_java::default]
      - recipe[bt_artifactory::default]
    attributes:
