
Vagrant::configure("2") do |config|

  # the Chef version to use
  config.omnibus.chef_version = "12.0.3"

  # disable vagrant-berkshelf
  config.berkshelf.enabled = false

  # common baseboxes for all VMs
  config.vm.box = "opscode-centos-6.5"

  #
  # app provisioned with v0.1.0 of the top-level cookbook
  #
  config.vm.define :'app1' do |config|
#    config.toplevel_cookbook.url = "https://github.com/tknerr/sample-toplevel-cookbook"
#    config.toplevel_cookbook.ref = "v0.1.0"
    config.toplevel_cookbook.url = "file:////home/john/work/BT/chef/top-level-cookbooks/bt_base"

    config.vm.hostname = "app1.local"

    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "build_base_image::default"
      chef.environments_path = "./environments"
      chef.environment = "local"
      chef.roles_path = "./roles"
    end
  end

end
