source 'https://supermarket.getchef.com'

metadata

cookbook 'bt_java', '~> 0.1.0', path: '/home/john/work/BT/chef/application-cookbooks/bt_java'
cookbook 'bt_ssh', '~> 0.1.0', path: '/home/john/work/BT/chef/application-cookbooks/bt_ssh'

